name: "Checkly Action"
description: "This action syncs a tests folder in your repo with a checkly check group."
inputs:
  checkly-token:
    required: true
    description: "Checkly Token"
  checkly-group:
    required: true
    description: "Checkly Check Group"
  checkly-account:
    required: true
    description: "Checkly Account ID"
  directory:
    required: false
    default: ./
    description: "if you want to modify the tests root directory"
  s3-key:
    required: false
    description: "if you want to use scripts with more than 1.000.000 chars"
  s3-key-id:
    required: false
    description: "key id matching the provided key"
  s3-bucket:
    required: false
    default: "checkly"
    description: "the s3 bucket to use for large scripts"
  s3-endpoint:
    required: false
    description: "the s3 endpoint to target"
  s3-region:
    required: false
    description: "the s3 region to target"
    default: auto
  max-script-size:
    required: false
    description: "the maximum amount of chars in a script before its loaded via S3"

runs:
  using: "node16"
  main: "action/index.js"
